#ifndef __CLT_EXPORT_H__
#define __CLT_EXPORT_H__

/* 
 * This file is automatically generated by the CExport plugin.
 * It contains the declaration of symbols that are required by
 * interface that was annotated with @CExport
 */

#include "mindcommon.h"

uint8_t clt_getNumber(void);

#endif //__CLT_EXPORT_H__

