#ifndef __SRV_EXPORT_H__
#define __SRV_EXPORT_H__
/* 
 * This file is automatically generated by the CExport plugin.
 * It contains the declaration of symbols to access the interface
 * that was annotated with @CExport
 */
 
#include "mindcommon.h"

uint8_t srv_getNumber(void);

#endif //__SRV_EXPORT_H__

